name: "Changelog Verifier"
on:
  push:
  workflow_dispatch:

jobs:
  # Test if docker loads 2 volumes correctly
  test-docker-volumes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test RPM package update stopping the indexer
        uses: addnab/docker-run-action@v3
        with:
          image: redhat/ubi9:latest
          options: 
            -v ${{ github.workspace }}/tools:/tools/
            -v ${{ github.workspace }}/build-scripts/:/build-scripts/
          run: |
            bash /build-scripts/indexer_node_install.sh "4.12.0"
            systemctl stop wazuh-indexer
            bash /tools/test.sh 