name: "Changelog Verifier"
on:
  push:
  workflow_dispatch:

jobs:
  # Test if docker loads 2 volumes correctly
  test-docker-volumes:
    runs-on: ubuntu-latest
    container: 
      image: redhat/ubi9:latest
                  
    run: |
      echo "Testing Docker volumes"